### ISSUE TITLE
Backpages with no child pages display an error in the sidebar, where the ancestor menu would be.

### ISSUE THREAD

**Issue by rebecca-patton** [wvuweb/wvu-design-system-liquid#3]
## Steps to reproduce the issue
1. Create a new top-level page using the Backpage page template
2. Open the page in edit mode or in a new tab and observe “Liquid error: internal” in the sidebar

## Results
Top-level backpages with no child pages display an error in the sidebar, instead of displaying nothing. This error only occurs on top-level backpages.

## Expected Results
If a top-level backpage has no child pages, no submenu or error message should be displayed.

## Examples of the Issue
- [https://prt.wvu.edu/downtime](https://prt.wvu.edu/downtime)
- [https://collegepark.wvu.edu/start-applying](https://collegepark.wvu.edu/start-applying)

**wvu-sidebar.html component:**  
- [https://github.com/wvuweb/wvu-design-system-liquid/blob/master/views/components/v2/_wvu-sidebar.html](https://github.com/wvuweb/wvu-design-system-liquid/blob/master/views/components/v2/_wvu-sidebar.html)

**Comment by nreckart** [comment]
This should now be fixed. Can someone else verify?

**Comment by rebecca-patton** [comment]
It's working correctly now 👍
